sudo: required

language: c

services:
  - docker

before_install:
- docker pull an4967/tizenrt:1.1
- echo "${TRAVIS_BUILD_DIR}"

script:
- docker run -d -it --name tizenrt_docker -v ${TRAVIS_BUILD_DIR}:/root/tizenrt -w /root/tizenrt/os an4967/tizenrt:1.1 /bin/bash
- docker exec tizenrt_docker make distclean
- docker exec -it tizenrt_docker bash -c 'cd tools; ./configure.sh artik053/nettest'
- docker exec -it tizenrt_docker bash -c 'export PATH=/root/gcc-arm-none-eabi-4_9-2015q3/bin:$PATH;make;'